venv/Scripts/pyinstaller.exe -n Pandemona -F --specpath release/build --distpath release --workpath release/build main.py;
mkdir -p release/Pandemona-0.x.x;
cp -R Resources release/Pandemona-0.x.x/;
cp -R "1 - InputFiles" release/Pandemona-0.x.x/;
mkdir -p "release/Pandemona-0.x.x/3 - OutputFiles";
mkdir -p "release/Pandemona-0.x.x/2 - PandemonaFiles";
cp release/*.exe release/Pandemona-0.x.x/;
cd release/Pandemona-0.x.x;
"C:\Program Files\7-Zip\7z.exe" a -tzip ../Pandemona-0.x.x.zip .;
cd ..;
rm -r Pandemona-0.x.x;
rm -r build;
rm *.exe;